#!/bin/bash

add-apt-repository ppa:charmers/charm-helpers
add-apt-repository ppa:nginx/stable

apt-get update && apt-get -y upgrade

apt-get -y install charm-helper-sh nginx mysql-client pwgen mailutils \
sysstat php5 php5-fpm php-apc php-mail php5-mcrypt php5-mysql \
php5-memcache php5-curl git-core rsync mktemp
